import type { MeasurementBookLine } from '@auto-mb/contracts';
import { MB_WAYS, type MbWay } from './mb-coefficient.js';
import {
  addDecimalStrings,
  multiplyDecimalStrings,
  renderQuantity,
} from './mb-remark.js';
import type { ParsedMeasurementItem } from './railway-measurement-parse.js';

/**
 * Whether the railway's measurement says what our Measurement Book says
 * (migration 0111).
 *
 * ## The grammar
 *
 * `railway-bill-verdict.ts` established the shape a verdict takes in this
 * product: a boolean the caller acts on, a NAMED refusal code, and one
 * sentence of detail that says what is wrong with THIS document and never
 * what to do about it — remedies belong to the remedy catalog. The same
 * three parts appear here, once per line rather than once per document,
 * and the document-level answer is derived from them.
 *
 * The difference from the bill's verdict is where the rule lives relative
 * to the data. A signature verdict is assessed on the way OUT, every time
 * it is read, because it is an owner ruling that must not need a data
 * migration to change. A match is assessed ONCE, at upload, and stored —
 * because it is a comparison against a Measurement Book that is itself
 * immutable, so re-running it can only ever produce the same answer, and
 * because a gate that re-derived its own precondition on every read would
 * change its answer whenever the matcher was edited. Migration 0111
 * states the same split.
 *
 * ## What is compared, and why exactly these two things
 *
 * THE MEASURED QUANTITY. The railway prints one `Total` per item, and it
 * is neither the stage quantity nor this measurement's own delta: it is
 * the TRUE CUMULATIVE quantity weighted by the stage percentage. MB-1 of
 * the settlement corpus states 2.1 for an item whose remark reads "70%
 * for 03 Nos", and MB-2 states 2.8 for the same item once one more unit
 * has been claimed. `expectedQuantity` below derives exactly that figure
 * from the Measurement Book's own line, in exact decimal arithmetic, and
 * carries the evidence for each half of the formula.
 *
 * THE RAILWAY FILES ITS SHEETS TWO WAYS, and since the owner's ruling on
 * corrections item 24 this matcher tries both rather than assuming the
 * one the corpus happens to be written in. The weighted figure above is
 * the "coefficient" way; the unweighted cumulative is the "physical" way
 * (`physicalQuantity` below states what it will and will not derive, and
 * why). Each line is judged against both and the verdict records WHICH
 * ONE the railway's figure was transcribed from, so the answer is
 * detected rather than assumed. Lines billed entirely at a single 100%
 * stage satisfy both, which is not a problem to be solved: the two
 * arithmetics genuinely coincide there.
 *
 * THE CONTRACTUAL REMARK. Our `Reason for Reduction` and theirs are the
 * same sentence — ours generated by `mb-remark.ts` under a pinned
 * template version, theirs re-typeset by IWRCMS — and the re-typesetting
 * is why the comparison is normalised rather than literal. Every
 * normalisation below is forced by a line in the committed corpus, and
 * none of them can turn one claim into another: what survives is the
 * percentages, the quantities and the words.
 *
 * What is deliberately NOT compared: the description and the unit. Both
 * are snapshots of master data IWRCMS re-renders in its own house style,
 * truncated with an ellipsis at about eighty characters on every item in
 * the corpus. Refusing on them would refuse every real document while
 * saying nothing about the measurement.
 */

/** Why one line does not match. A code the screen turns into a sentence
 * and the route reports; each names a different thing that went wrong. */
export type MeasurementLineRefusal =
  'quantity' | 'remark' | 'missing_from_measurement' | 'absent_from_measurement_book';

export interface MeasurementLineVerdict {
  /** The Measurement Book's item number, or — for an item the railway
   * carries and the book does not — the railway document's. */
  readonly itemNumber: string;
  readonly matched: boolean;
  readonly refusal: MeasurementLineRefusal | null;
  /** One sentence naming what differs on THIS line. Never a remedy. */
  readonly detail: string | null;
  /** WHICH WAY the railway's figure was transcribed from, detected rather
   * than assumed (owner ruling, corrections item 24): `coefficient` when
   * the printed total is the stage-weighted quantity, `physical` when it
   * is the unweighted one. Null on a line that fits neither, and on the
   * two structural refusals, where there is no figure to read a way off.
   *
   * A line billed entirely at a single 100% stage fits both ways, because
   * the two arithmetics coincide there. The tie is broken towards the way
   * the Measurement Book itself records (migration 0113) — the sheet was
   * typed from that book, so its own statement is the best evidence
   * available about a figure that cannot distinguish them. */
  readonly way: MbWay | null;
}

export interface MeasurementMatch {
  /** `matched` only when every line matched and neither document carries
   * an item the other does not. */
  readonly status: 'matched' | 'mismatched';
  readonly lines: readonly MeasurementLineVerdict[];
}

/** The four stages a Measurement Book line can claim: this book's delta,
 * everything billed before it, and the percentage both are weighted by. */
const STAGES = [
  ['deltaSupplied', 'priorSupplied', 'pctSupply'],
  ['deltaInstalled', 'priorInstalled', 'pctInstallation'],
  ['deltaPac', 'priorPac', 'pctPac'],
  ['deltaFinalBill', 'priorFinalBill', 'pctFinalBill'],
] as const;

/**
 * The figure the railway's `Total` should read for one Measurement Book
 * line: Σ over stages of (prior + delta) × percent / 100, exactly.
 *
 * THE PRIOR IS IN THERE, and it is the correction the real corpus forced.
 * The obvious reading — that the railway's total is this measurement's own
 * quantity — holds on MB-1 of the settlement corpus, where every prior is
 * zero, and fails on the next document: MB-2 item A/01 reads "Prepaid 70%
 * for 03 Nos Now to Pay 70% for 01 Nos" and states a Total of 2.8, which
 * is 0.7 × 4 and not 0.7 × 1. MB-3 makes it unmistakable — item A/01 reads
 * "Now to Pay Nil" and still states 2.8. The railway prints the TRUE
 * CUMULATIVE, which is the same quantity this product's own Measurement
 * Book lines carry as `prior_* + delta_*`, and a matcher built on the
 * first document alone would have refused every second and third
 * measurement of every Work.
 *
 * Exact rather than floating: this is an authoritative comparison and a
 * rounding error here refuses a document that agrees (AGENTS.md rule 5).
 * The division by 100 is done by multiplying by the decimal string
 * `0.01`, so no integer division and no truncation enters at all.
 */
function expectedQuantity(line: MeasurementBookLine): string {
  let total = '0';
  for (const [delta, prior, percent] of STAGES) {
    const cumulative = addDecimalStrings(line[prior], line[delta]);
    total = addDecimalStrings(
      total,
      multiplyDecimalStrings(multiplyDecimalStrings(cumulative, line[percent]), '0.01'),
    );
  }
  return total;
}

/**
 * THE OTHER FIT (owner ruling, corrections item 24): the figure a way-2
 * sheet would print for this line — the PHYSICAL cumulative quantity, with
 * no stage percentage applied.
 *
 * Returns null where the line has no single physical quantity to state,
 * and that restriction is the whole care taken here. Every document in the
 * committed settlement corpus is way 1, so there is not one example of how
 * IWRCMS prints a way-2 line whose stages carry DIFFERENT cumulative
 * quantities — 3 supplied and 2 installed is one physical measurement of
 * three units and one of two, and whether the sheet totals 3, 2 or 5 is a
 * question the corpus cannot answer. Guessing it is how a matcher starts
 * accepting documents that do not agree, which is the argument this module
 * already makes about print precision. So the physical fit is offered only
 * where every stage carrying quantity carries the SAME one — which is
 * every single-stage line, and therefore very nearly every line — and a
 * line where the stages disagree simply has no second fit to try. It is
 * then judged on the coefficient fit alone, exactly as it was before this
 * ruling.
 *
 * Stages carrying nothing are skipped rather than counted as zero: a
 * percentage-bearing stage that has billed nothing says nothing about the
 * quantity measured on the ones that have.
 */
function physicalQuantity(line: MeasurementBookLine): string | null {
  let physical: string | null = null;
  for (const [delta, prior] of STAGES) {
    const cumulative = addDecimalStrings(line[prior], line[delta]);
    if (renderQuantity(cumulative) === '0') continue;
    if (physical === null) {
      physical = cumulative;
      continue;
    }
    if (renderQuantity(physical) !== renderQuantity(cumulative)) return null;
  }
  // Every stage empty: the book measures nothing on this line and both
  // ways print the same nothing.
  return physical ?? '0';
}

/**
 * The fits to try, in the order they are tried: the Measurement Book's own
 * recorded way first (migration 0113), then the other.
 *
 * ORDER IS THE TIE-BREAK AND NOTHING ELSE. Both fits are computed and both
 * are compared; the order only decides which name a figure satisfying BOTH
 * is recorded under, which is the single-100%-stage case where the two
 * arithmetics coincide. A figure satisfying exactly one is named by that
 * one whichever way the book claims — the point of trying both is that the
 * railway's typist, not our book, decided what went on the sheet.
 */
function fitsInPreferenceOrder(
  line: MeasurementBookLine,
  recordedWay: MbWay,
): ReadonlyArray<{ readonly way: MbWay; readonly quantity: string }> {
  const byWay: Record<MbWay, string | null> = {
    coefficient: expectedQuantity(line),
    physical: physicalQuantity(line),
  };
  const ordered = [recordedWay, ...MB_WAYS.filter((way) => way !== recordedWay)];
  return ordered.flatMap((way) => {
    const quantity = byWay[way];
    return quantity === null ? [] : [{ way, quantity }];
  });
}

/**
 * The remark, reduced to the claim it carries.
 *
 * Five differences between our wording and IWRCMS's, every one of them
 * observed in `test/fixtures/railway-settlement/MB-{1,2}.raw.txt`:
 *
 *   1. CASE. Ours "Now to pay", theirs "Now to Pay".
 *   2. ZERO PADDING. Ours "for 3 Nos", theirs "for 03 Nos".
 *   3. PUNCTUATION. Ours ends each clause with a full stop; theirs has
 *      none.
 *   4. SPACING. MB-2 prints "Prepaid70% for 09 Nos" — no space after the
 *      label — on one item and "Prepaid 64% for 01 Nos" on the next, in
 *      the same document. Whitespace is therefore removed entirely
 *      rather than collapsed.
 *   5. "nill" / "Nil". Ours spells the nothing-to-pay case "nill" with
 *      two Ls (`mb-remark.ts`, deliberately, and the owner declined to
 *      change it); theirs spells it "Nil".
 *
 * The prepaid clause is the sixth difference and it is handled by the
 * caller-visible rule below rather than here: our engine OMITS "Prepaid
 * Nil" on an item's first-ever billing while IWRCMS prints it, so a
 * leading "prepaidnil" is dropped from either side.
 *
 * What is left is digits, percent signs and letters — the percentages,
 * the quantities and the unit words. Nothing that could turn one claim
 * into a different one survives being removed.
 */
function normaliseRemark(value: string): string {
  const reduced = value
    // Leading zeros inside a number, but not the zero of "0.64": the
    // lookahead requires a digit to follow, and the guard behind stops
    // this reaching the decimal fraction of a longer figure.
    .replaceAll(/(?<![\d.])0+(\d)/g, '$1')
    .toLowerCase()
    .replaceAll(/[^a-z0-9%]/g, '')
    .replaceAll('nill', 'nil');
  return reduced.startsWith('prepaidnil')
    ? reduced.slice('prepaidnil'.length)
    : reduced;
}

/** `A/01` and `A/1` are one item. The railway zero-pads its item numbers
 * and this product's schedules do not; nothing else about the key is
 * folded, because a schedule letter is not a number and `A/1` must never
 * be read as `B/1`. */
function normaliseItemNumber(value: string): string {
  return value
    .trim()
    .toUpperCase()
    .split('/')
    .map((segment) => (/^\d+$/.test(segment) ? String(Number(segment)) : segment))
    .join('/');
}

function matched(itemNumber: string, way: MbWay): MeasurementLineVerdict {
  return { itemNumber, matched: true, refusal: null, detail: null, way };
}

function mismatched(
  itemNumber: string,
  refusal: MeasurementLineRefusal,
  detail: string,
): MeasurementLineVerdict {
  return { itemNumber, matched: false, refusal, detail, way: null };
}

/**
 * Compares a parsed railway measurement against the Measurement Book's
 * own stored lines.
 *
 * The Book's order is the output's order — it is the document the
 * operator is reconciling FROM — with any item the railway carries and
 * the book does not appended at the end, because a quantity on the
 * railway's sheet against an item we never measured is exactly as much of
 * a disagreement as a missing one and must not be silently dropped.
 *
 * `recordedWay` is the way the Measurement Book itself was filed
 * (migration 0113). It is NOT a filter: both fits are tried on every line
 * and a line that agrees only the other way still matches, and is recorded
 * as having been transcribed that way. It only decides the name given to a
 * figure that satisfies both — see `fitsInPreferenceOrder`.
 */
export function matchRailwayMeasurement(
  bookLines: readonly MeasurementBookLine[],
  measurementItems: readonly ParsedMeasurementItem[],
  recordedWay: MbWay,
): MeasurementMatch {
  const byItem = new Map<string, ParsedMeasurementItem>();
  for (const item of measurementItems) {
    byItem.set(normaliseItemNumber(item.itemNumber), item);
  }

  const verdicts: MeasurementLineVerdict[] = [];
  const seen = new Set<string>();

  for (const line of bookLines) {
    const key = normaliseItemNumber(line.itemNumber);
    const found = byItem.get(key);
    if (found === undefined) {
      verdicts.push(
        mismatched(
          line.itemNumber,
          'missing_from_measurement',
          `Item ${line.itemNumber} is measured in this Measurement Book and does not appear on the railway's measurement.`,
        ),
      );
      continue;
    }
    seen.add(key);

    const fits = fitsInPreferenceOrder(line, recordedWay);
    const fit = fits.find(
      (candidate) =>
        renderQuantity(found.quantity) === renderQuantity(candidate.quantity),
    );
    // ponytail: EXACT equality, and the ceiling is the railway's printer
    // rather than the arithmetic. Every quantity in the settlement corpus
    // is exact — the stage quantities are whole units and the products
    // land on one or two decimals — so nothing real is refused today. The
    // case that would be is a FRACTIONAL quantity times a percentage that
    // does not terminate: 3.333 Mtr at 64% is exactly 2.13312, IWRCMS
    // prints 2.133, and this comparison would call a document that agrees
    // a mismatch. The upgrade path is a print-precision-aware compare —
    // accept a printed value that is the correct rounding of the exact
    // product to the number of decimals it actually printed — and it is
    // deliberately not built here, because guessing the railway's
    // rounding rule from zero examples of it is how a matcher starts
    // accepting documents that do not agree. Build it against the first
    // real fractional-quantity sheet, which will also say which way it
    // rounds.
    if (fit === undefined) {
      // The refusal names EVERY figure the book could honestly have been
      // transcribed into, because "we measure 2.1, you record 3" reads as
      // a disagreement about quantity when it is really a disagreement
      // about which way the sheet was filled — and an operator who can see
      // both numbers can tell those apart in a second.
      const measured = fits
        .map((candidate) => `${renderQuantity(candidate.quantity)} (${candidate.way})`)
        .join(' or ');
      verdicts.push(
        mismatched(
          line.itemNumber,
          'quantity',
          `Item ${line.itemNumber}: this Measurement Book measures ${measured}, the railway's measurement records ${renderQuantity(found.quantity)}.`,
        ),
      );
      continue;
    }

    if (normaliseRemark(found.remark) !== normaliseRemark(line.remark)) {
      verdicts.push(
        mismatched(
          line.itemNumber,
          'remark',
          `Item ${line.itemNumber}: this Measurement Book reads "${line.remark}", the railway's measurement reads "${found.remark}".`,
        ),
      );
      continue;
    }

    verdicts.push(matched(line.itemNumber, fit.way));
  }

  for (const item of measurementItems) {
    if (seen.has(normaliseItemNumber(item.itemNumber))) continue;
    verdicts.push(
      mismatched(
        item.itemNumber,
        'absent_from_measurement_book',
        `Item ${item.itemNumber} appears on the railway's measurement and is not measured in this Measurement Book.`,
      ),
    );
  }

  return {
    status: verdicts.every((verdict) => verdict.matched) ? 'matched' : 'mismatched',
    lines: verdicts,
  };
}
